create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(12, 2) not null default 0,
  category text,
  image_url text,
  stock integer not null default 0,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.products
  add column if not exists featured boolean not null default false;

create index if not exists products_featured_created_at_idx
  on public.products (featured desc, created_at desc);

create table if not exists public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  author text,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  user_name text not null,
  rating integer not null check (rating between 1 and 5),
  comment text not null,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.ads (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text,
  start_date date,
  end_date date,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  shipping_address text not null,
  total_price numeric(12, 2) not null default 0,
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  price_at_purchase numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.products enable row level security;
alter table public.blogs enable row level security;
alter table public.reviews enable row level security;
alter table public.ads enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Public can read products"
  on public.products for select
  using (true);

create policy "Public can read blogs"
  on public.blogs for select
  using (true);

create policy "Public can read approved reviews"
  on public.reviews for select
  using (approved = true);

create policy "Public can read active ads"
  on public.ads for select
  using (active = true);
